<?php

return [
    [
        'user_id' => '1',
        'title' => 'Il tuo Sogno',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '85',
        'address' => 'Via della Scala, 3, Firenze',
        'latitude' => '43.7732317',
        'longitude' => '11.2465212',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Suite Ognissanti Firenze',
        'slug' => '',
        'rooms' => '6',
        'beds' => '1',
        'bathrooms' => '2',
        'square_meters' => '92',
        'address' => 'Via delle Porte Nuove, 2, Firenze',
        'latitude' => '43.7799492',
        'longitude' => '11.2403348',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Florence Santa Croce - Quiet',
        'slug' => '',
        'rooms' => '5',
        'beds' => '1',
        'bathrooms' => '2',
        'square_meters' => '80',
        'address' => 'Via Faenza, 71, Firenze',
        'latitude' => '43.777791',
        'longitude' => '11.251058',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Maison Brunelleschi - 50m dal Duomo, Ascensore',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '102',
        'address' => 'Via Rosina, 4, Firenze',
        'latitude' => '43.776646',
        'longitude' => '11.254669',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '1',
        'title' => 'Traveller Nest: il nido dei viaggiatori',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '85',
        'address' => 'Via Ricasoli, 39, Firenze',
        'latitude' => '43.776442',
        'longitude' => '11.258267',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '2',
        'title' => 'APPARTAMENTO CENTRO STORICO FIRENZE',
        'slug' => '',
        'rooms' => '7',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '120',
        'address' => 'Via dei Servi, 15, Firenze',
        'latitude' => '43.774627',
        'longitude' => '11.2587816',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '2',
        'title' => 'Love the Space',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '90',
        'address' => 'Via del Castellaccio, 13, Firenze',
        'latitude' => '43.7752982',
        'longitude' => '11.2576016',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '2',
        'title' => 'SUITE PICCOLO PRINCIPE, Polimoda',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '65',
        'address' => 'Via della Pergola, 45, Firenze',
        'latitude' => '43.7749031',
        'longitude' => '11.262109',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '2',
        'title' => 'Florence room',
        'slug' => '',
        'rooms' => '5',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '73',
        'address' => 'Via della Colonna, 11-5, Firenze',
        'latitude' => '43.7745931',
        'longitude' => '11.2645551',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '2',
        'title' => 'Casa con grande terrazza',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '125',
        'address' => 'Via Giovan Battista Niccolini, 32, Firenze',
        'latitude' => '43.7731466',
        'longitude' => '11.2677746',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '3',
        'title' => 'Punto nel Cuore - Appartamento',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'address' => 'Via Pietro Colletta, 2, Firenze',
        'latitude' => '43.7731466',
        'longitude' => '11.2677746',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '3',
        'title' => 'Valia Florence Pitti accanto a Palazzo Pitti',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '95',
        'address' => 'Via Luca Landucci, 34, Firenze',
        'latitude' => '43.7722675',
        'longitude' => '11.2754472',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '3',
        'title' => 'Dante&Beatrice Flat - Santa Maria Novella',
        'slug' => '',
        'rooms' => '9',
        'beds' => '3',
        'bathrooms' => '3',
        'square_meters' => '175',
        'address' => 'Via Giovanni Paisiello, 27, Firenze',
        'latitude' => '43.7817652',
        'longitude' => '11.2298328',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '3',
        'title' => 'Apartment By Villa Il Mosaico',
        'slug' => '',
        'rooms' => '5',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '100',
        'address' => 'Via delle Porte Nuove, 15, Firenze',
        'latitude' => '43.7792043',
        'longitude' => '11.238969',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '3',
        'title' => 'Elegante, Romantico, Confortevole Appartamento!',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '96',
        'address' => 'Via Iacopo da Diacceto, 40, Firenze',
        'latitude' => '43.778400',
        'longitude' => '11.243600',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '4',
        'title' => 'Moderno e Funzionale Monolocale',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'address' => 'Via Luigi Alamanni, 5, Firenze',
        'latitude' => '43.7769279',
        'longitude' => '11.2452965',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '4',
        'title' => 'IL MAGNIFICO - Home in Florence',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '102',
        'address' => 'Via del Alloro, 4, Firenze',
        'latitude' => '43.7739901',
        'longitude' => '11.2513614',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '4',
        'title' => 'I tre cipressi',
        'slug' => '',
        'rooms' => '4',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '86',
        'address' => 'Via dei Cerretani, 29 R, Firenze',
        'latitude' => '43.7733871',
        'longitude' => '11.2512322',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '4',
        'title' => 'Bilocale - Santo Spirito',
        'slug' => '',
        'rooms' => '6',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '95',
        'address' => 'Via del Oriuolo, 66, Firenze',
        'latitude' => '43.771401',
        'longitude' => '11.2559798',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Porta Nera - Private Living',
        'slug' => '',
        'rooms' => '7',
        'beds' => '5',
        'bathrooms' => '3',
        'square_meters' => '250',
        'address' => 'Via dei Federighi, 15, 50123 Firenze FI',
        'latitude' => '43.771637',
        'longitude' => '11.249239',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Residenza Ognissanti',
        'slug' => '',
        'rooms' => '2',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '75',
        'address' => 'Borgo Ognissanti, 80, 50123 Firenze FI',
        'latitude' => '43.773567',
        'longitude' => '11.24417',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'HomeResidence la Contessina',
        'slug' => '',
        'rooms' => '4',
        'beds' => '4',
        'bathrooms' => '2',
        'square_meters' => '120',
        'address' => 'Via Faenza, 71, 50123 Firenze FI',
        'latitude' => '43.775274',
        'longitude' => '11.252546',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Ape Rosa Relais',
        'slug' => '',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '45',
        'address' => 'Via dei Cappuccini, 12, 50134 Firenze FI',
        'latitude' => '43.792922',
        'longitude' => '11.250504',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'B&B Hotel Firenze Nuovo Palazzo di Giustizia',
        'slug' => '',
        'rooms' => '12',
        'beds' => '18',
        'bathrooms' => '12',
        'square_meters' => '862',
        'address' => 'Viale Alessandro Guidoni, 87, 50127 Firenze FI',
        'latitude' => '43.797322',
        'longitude' => '11.220807',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Flor in Florence',
        'slug' => '',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '95',
        'address' => 'Via Giorgio la Pira, 21, 50121 Firenze FI',
        'latitude' => '43.779808',
        'longitude' => '11.260814',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'La Maison du Sage',
        'slug' => '',
        'rooms' => '3',
        'beds' => '3',
        'bathrooms' => '2',
        'square_meters' => '60',
        'address' => 'Via Antonio Magliabechi, 7, 50122 Firenze FI',
        'latitude' => '43.768093',
        'longitude' => '11.261511',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Residenza Cantagalli',
        'slug' => '',
        'rooms' => '1',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '80',
        'address' => 'Via Cantagalli, 4, 50125 Firenze FI',
        'latitude' => '43.758637',
        'longitude' => '11.241648',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Torre di Bellosguardo',
        'slug' => '',
        'rooms' => '8',
        'beds' => '16',
        'bathrooms' => '8',
        'square_meters' => '240',
        'address' => 'Via Roti Michelozzi, 2, 50125 Firenze FI',
        'latitude' => '43.763865',
        'longitude' => '11.232913',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'AC Hotel Firenze by Marriott',
        'slug' => '',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '35',
        'address' => 'Via Luciano Bausi, 5, 50144 Firenze FI',
        'latitude' => '43.779681',
        'longitude' => '11.237173',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'San Firenze Suites & Spa',
        'slug' => '',
        'rooms' => '6',
        'beds' => '6',
        'bathrooms' => '6',
        'square_meters' => '152',
        'address' => 'Piazza di S. Firenze, 3, 50122 Firenze FI',
        'latitude' => '43.770513',
        'longitude' => '11.25256',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Orto De Medici',
        'slug' => '',
        'rooms' => '2',
        'beds' => '4',
        'bathrooms' => '2',
        'square_meters' => '82',
        'address' => 'Via S. Gallo, 30, 50129 Firenze FI',
        'latitude' => '43.778805',
        'longitude' => '11.257628',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Torre Guelfa',
        'slug' => '',
        'rooms' => '1',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '95',
        'address' => 'Borgo Santi Apostoli, 8, 50123 Firenze FI',
        'latitude' => '43.76923',
        'longitude' => '11.252935',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Leone Blu',
        'slug' => '',
        'rooms' => '4',
        'beds' => '4',
        'bathrooms' => '2',
        'square_meters' => '140',
        'address' => 'Piazza Carlo Goldoni, 2, 50123 Firenze FI',
        'latitude' => '43.770873',
        'longitude' => '11.248032',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Alba Palace',
        'slug' => '',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '36',
        'address' => 'Via della Scala, 22, 50123 Firenze FI',
        'latitude' => '43.774377',
        'longitude' => '11.247325',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Social Hub Florence Lavagnini',
        'slug' => '',
        'rooms' => '7',
        'beds' => '14',
        'bathrooms' => '4',
        'square_meters' => '172',
        'address' => 'V.le Spartaco Lavagnini, 70-72, 50129 Firenze FI',
        'latitude' => '43.782093',
        'longitude' => '11.253457',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Quadra Key Easy Home in Florence',
        'slug' => '',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '74',
        'address' => 'Via di Novoli, 87, 50127 Firenze FI',
        'latitude' => '43.793689',
        'longitude' => '11.218872',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'My Rooms firenze',
        'slug' => '',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '80',
        'address' => 'Via Lippi e Macia, 24, 50127 Firenze FI',
        'latitude' => '43.79705',
        'longitude' => '11.219339',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Casale Argentina',
        'slug' => '',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '76',
        'address' => 'Corso Vittorio Emanuele II, 102, 00186 Roma RM',
        'latitude' => '41.896173',
        'longitude' => '12.475938',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'La Corte di Cloris',
        'slug' => '',
        'rooms' => '4',
        'beds' => '4',
        'bathrooms' => '4',
        'square_meters' => '210',
        'address' => 'Via Masaccio, 234, 50132 Firenze FI',
        'latitude' => '43.783261',
        'longitude' => '11.268572',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Villa Agape',
        'slug' => '',
        'rooms' => '18',
        'beds' => '24',
        'bathrooms' => '20',
        'square_meters' => '1250',
        'address' => 'Via della Torre del Gallo, 8, 50125 Firenze FI',
        'latitude' => '43.750305 ',
        'longitude' => '11.257547',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Villa la Stella',
        'slug' => '',
        'rooms' => '6',
        'beds' => '8',
        'bathrooms' => '6',
        'square_meters' => '280',
        'address' => 'Via Iacopone da Todi, 12, 50133 Firenze FI',
        'latitude' => '43.794217',
        'longitude' => '11.283536',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Villa sull Arno',
        'slug' => '',
        'rooms' => '6',
        'beds' => '6',
        'bathrooms' => '6',
        'square_meters' => '195',
        'address' => 'Lungarno Cristoforo Colombo, 1, 50136 Firenze FI',
        'latitude' => '43.766143',
        'longitude' => '11.284365',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'B&B Cimabue 9',
        'slug' => '',
        'rooms' => '1',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '57',
        'address' => 'Via Cimabue, 9, 50121 Firenze FI',
        'latitude' => '43.768496',
        'longitude' => '11.272771',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Horto Convento Firenze',
        'slug' => '',
        'rooms' => '14',
        'beds' => '28',
        'bathrooms' => '14',
        'square_meters' => '482',
        'address' => 'Viale Ludovico Ariosto, 13, 50124 Firenze FI',
        'latitude' => '43.76921',
        'longitude' => '11.239744',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Suites Lungarno Vespucci 50',
        'slug' => '',
        'rooms' => '6',
        'beds' => '6',
        'bathrooms' => '6',
        'square_meters' => '180',
        'address' => 'Lungarno Amerigo Vespucci, 50, 50123 Firenze FI',
        'latitude' => '43.772055',
        'longitude' => '11.244927',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Villa Sonnino',
        'slug' => '',
        'rooms' => '4',
        'beds' => '6',
        'bathrooms' => '4',
        'square_meters' => '259',
        'address' => 'Via Castelvecchio, 9, 56028 San Miniato PI',
        'latitude' => '43.685012',
        'longitude' => '10.812856',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Florence Country Relais',
        'slug' => '',
        'rooms' => '3',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '185',
        'address' => 'Via dei Bosconi, 50014 Fiesole, FI',
        'latitude' => '43.837657',
        'longitude' => '11.333016',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Hospalita',
        'slug' => '',
        'rooms' => '1',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '70',
        'address' => 'Via Vittorio Locchi, 17, 50141 Firenze FI',
        'latitude' => '43.806557',
        'longitude' => '11.234578',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'LILIUM - Firenze Centro Storico',
        'slug' => '',
        'rooms' => '12',
        'beds' => '14',
        'bathrooms' => '12',
        'square_meters' => '695',
        'address' => 'Via Fiume, 17, 50123 Firenze FI',
        'latitude' => '43.777562',
        'longitude' => '11.249603',
        'cover_image' => '',
        'visible' => true
    ],
    [
        'user_id' => '5',
        'title' => 'Eden B&B',
        'slug' => '',
        'rooms' => '1',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '42',
        'address' => 'Via Nazionale, 55, 50123 Firenze FI',
        'latitude' => '44.060007',
        'longitude' => '11.262964',
        'cover_image' => '',
        'visible' => true
    ]
];
